sudo: required 
services:
        - docker

before_install:
        - docker build -t uelfar/docker-react -f Dockerfile.dev .
script:
        - docker run uelfar/docker-react npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: eu-west-1
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-eu-west-1-754816623387"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY

