sudo: required 
services:
        - docker

before_install:
        - docker build -t uelfar/docker-react -f Dockerfile.dev .
script:
        - docker run uelfar/docker-react npm run test -- --coverage
